# Generated by Django 5.2.2 on 2025-06-16 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('latitude', models.CharField(max_length=128)),
                ('longitude', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('materials', models.CharField(max_length=128)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts_museum', to='game.museum')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts_country', to='game.country')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32)),
                ('round_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts_round_1', to='game.artifact')),
                ('round_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts_round_2', to='game.artifact')),
                ('round_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts_round_3', to='game.artifact')),
            ],
        ),
    ]
