# Generated by Django 5.2.2 on 2025-06-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_country_artifact_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='description',
            field=models.CharField(max_length=1280),
        ),
    ]
