# Generated by Django 5.2.2 on 2025-06-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_country_latitude_alter_country_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='latitude',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.CharField(max_length=128),
        ),
    ]
