# Generated by Django 5.2.2 on 2025-06-17 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_country_latitude_alter_country_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.artifact'),
        ),
        migrations.AlterField(
            model_name='game',
            name='round_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.artifact'),
        ),
        migrations.AlterField(
            model_name='game',
            name='round_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.artifact'),
        ),
    ]
