# Generated by Django 5.2.2 on 2025-06-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_round_1_alter_game_round_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='artist',
            field=models.CharField(default='Unknown', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifact',
            name='image',
            field=models.ImageField(default='static/game/artifact1.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
