# Generated by Django 5.2.2 on 2025-06-18 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_game_round_1_alter_game_round_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_1_artifact', to='game.artifact'),
        ),
        migrations.AlterField(
            model_name='game',
            name='round_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_2_artifact', to='game.artifact'),
        ),
        migrations.AlterField(
            model_name='game',
            name='round_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_3_artifact', to='game.artifact'),
        ),
    ]
