# Generated by Django 5.2.2 on 2025-06-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_game_round_1_alter_game_round_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.ImageField(upload_to='artifactle/media/artifacts'),
        ),
    ]
