# Generated by Django 5.2.3 on 2025-06-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_artifact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
