# Generated by Django 5.2.3 on 2025-07-03 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_artifact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_1_artifact', to='game.artifact', unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='round_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_2_artifact', to='game.artifact', unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='round_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_3_artifact', to='game.artifact', unique=True),
        ),
    ]
